exclude: 'docs|node_modules|migrations|.git|.tox'
default_stages: [commit]
fail_fast: true
default_language_version:
    python: python3.7

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: check-merge-conflict
    -   id: end-of-file-fixer
    -   id: debug-statements
        name: check for python debug statements
        description: Check for debugger imports and py37+ `breakpoint()` calls in python source.
    -   id: check-yaml
        name: check for yaml files
        description: Check configurations for yaml files
    -   id: detect-private-key
        name: check for private key
        description: Check for preventing pushing private keys to the version control


-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.4
    hooks:
    -   id: flake8
        args: ['--config=setup.cfg']

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.790
    hooks:
    -   id: mypy
        exclude: test*
        args: ['--config-file=setup.cfg']

-   repo: https://github.com/pycqa/isort
    rev: 5.5.2
    hooks:
      - id: isort
        args: ['--settings-path=setup.cfg']
